version: '3'
volumes:
  postgres_data:
    driver: local
services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  guardian-newspaper:
    build: .
    image: guardian-newspaper
    container_name: guardian-newspaper
    network_mode: host
    ports:
      - 3001:3001
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: nestdb
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      JWT_SECRET: make-one
      GUARDIAN_BASEURL: https://content.guardianapis.com
      GUARDIAN_API_KEY: test
